Repository yiisoft/data-db, pull requests merged in 2024-05, with the labels that each got.

#52 Fix tests + Update PhpUnit
  .gitignore
  composer.json
  phpunit.xml.dist
  tests/DataFilterTest.php
  tests/DataReaderTest.php
  tests/QueryWithFiltersTest.php
  tests/Support/Stub/Column.php
  tests/Support/Stub/ColumnSchema.php
  tests/Support/Stub/Command.php
  tests/Support/Stub/Connection.php
  tests/Support/Stub/DDLQueryBuilder.php
  tests/Support/Stub/DMLQueryBuilder.php
  tests/Support/Stub/DQLQueryBuilder.php
  tests/Support/Stub/Dsn.php
  tests/Support/Stub/DsnSocket.php
  tests/Support/Stub/PdoDriver.php
  tests/Support/Stub/QueryBuilder.php
  tests/Support/Stub/Schema.php
  tests/Support/Stub/TableSchema.php
  tests/Support/Stub/Transaction.php
  tests/Support/TestTrait.php
Labels: status:code review

#53 Fix docs
  CHANGELOG.md
  README.md
  composer.json
Labels: type:docs, type:task, dependencies

#54 Fix docs
  README.md
  composer.json
Labels: type:docs, type:task, dependencies

#56 Test all supported RDMBS, tests' refactoring
  .github/workflows/build.yml
  .github/workflows/mssql.yml
  .github/workflows/mysql.yml
  .github/workflows/oracle.yml
  .github/workflows/pgsql.yml
  .github/workflows/sqlite.yml
  composer.json
  phpunit.xml.dist
  tests/.env
  tests/Base/QueryDataReaderTest.php
  tests/Base/TestCase.php
  tests/DataFilterTest.php
  tests/DataReaderTest.php
  tests/Mssql/DatabaseTrait.php
  tests/Mssql/QueryDataReaderTest.php
  tests/Mysql/DatabaseTrait.php
  tests/Mysql/QueryDataReaderTest.php
  tests/Oracle/DatabaseTrait.php
  tests/Oracle/QueryDataReaderTest.php
  tests/Pgsql/DatabaseTrait.php
  tests/Pgsql/QueryDataReaderTest.php
  tests/QueryWithFiltersTest.php
  tests/Sqlite/DatabaseTrait.php
  tests/Sqlite/QueryDataReaderTest.php
  tests/Support/Assert.php
  tests/Support/Cache.php
  tests/Support/CustomerDataReader.php
  tests/Support/CustomerQuery.php
  tests/Support/DbHelper.php
  tests/Support/TestTrait.php
  tests/Support/TraversableObject.php
  tests/bootstrap.php
  tests/docker-compose.yml
Labels: type:task
